version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
  backend1:
    build:
      context: ./backend1
    ports:
      - "3000:3000"
  backend2:
    build:
      context: ./backend2
    ports:
      - "3001:3000"
  krakend_ce:
    image: devopsfaith/krakend:1.3.0
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    depends_on:
      - jaeger
